language: python2
python:
  - "2.7"

install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt

script:
  - pip install coveralls
  - coverage run --source=complic setup.py test
  - coveralls

