language: python2
python:
  - "2.7"

install:
  - pip install --user -r requirements-dev.txt
  - pip install --user -r requirements.txt
  - pip install --user coveralls

script:
  - coverage run setup.py test
  - coveralls
