language: python2
python:
  - "2.7"

install:
  - pip install --user -r requirements-dev.txt
  - pip install --user -r requirements.txt

script:
  - pip install --user coveralls
  - coverage run --source=complic setup.py test
  - coveralls

